from django.contrib.auth import logout
from django.shortcuts import render

# from csci4830.libraryshop.models import BookSection


# Also look at urls.py
# Visit the very top directory (/)


def index(request):
    from libraryshop.models import Book
    """This is the function that is executed when the root (/) url is called.

    It is called in urls.py (in the csci4830 controller folder, the last one)
    """
    varSetInViews = "Please check views.py to see the variable for this string."

    # The following line queries the database for all the book objects , then prints their ID numbers generated by django
    for book in Book.objects.all():
        print(book.id)

    # We pass this to render() in the return statement to give the template variable values to insert in the html
    context = {
        "passedVariableFromRender":  varSetInViews,
        'pagetitle': "Index File",
    }

    return render(request, "skeleton.html", context)


def book(request):
    from libraryshop.models import Book
    # This will list all the book genres and print it in an unordered list, for example purposes
    allGenres = Book.ENUM_GENRES
  # Note how resultstring is initalized as a string?
    resultstr = '<ul>'

   # For (each) loop going through every genre, wrapping string with html list elements
    for book in allGenres:
        resultstr += "<li>" + book[1] + "</li>"
    resultstr += '</ul>'

    # Context variable. Note the pagetitle and passedVariableFromRender? You'll see them in the template files between braces: {{ pagetitle }}
    context = {
        'pagetitle': "Book page",
        # Note that HTML isn't escaped because |safe is mark in the skeleton.html template.
        'passedVariableFromRender': resultstr
    }

    # We are using the base template skeleton.html, which is in the templates folder
    return render(request, "skeleton.html", context)


def search(request):
    from libraryshop.forms import SearchBookForm
    form = SearchBookForm()

    context = {
        'passedVariableFromRender': form
    }
    return render(request, "skeleton.html", context)


def browse(request):

    pass


######

def login(request):
    from libraryshop.models import User
    from django.contrib.auth import authenticate, login

    login_status_mesg = ''
    postUsername = request.POST.get('username')
    postPassword = request.POST.get('password')
    session_user = None

    if User.objects.filter(username=postUsername).count() == 0:
        login_status_mesg += 'User does not exist!'
    elif (session_user := authenticate(request, username=postUsername, password=postPassword)) == None:
        login_status_mesg += 'Invalid username and password combination!'
    # else:
        #login_status_mesg += 'Invalid username and password combination!'

    print(login_status_mesg)
    from libraryshop.forms import LoginForm
    a = LoginForm

    context = {
        'user': session_user,
        'login_form': LoginForm(),
        'content_site': 'login.html',
        'login_status_mesg': login_status_mesg
    }
    print(context[1])
    return render(request, "registration/login.html", context)


def logout_view(request):
    logout(request)
