# Generated by Django 3.2.9 on 2021-11-14 03:11

from django.db import migrations, models
import django.db.models.deletion
import libraryshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryshop', '0002_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryshop.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to=libraryshop.models.Book.cover_image_path),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryshop.useraccount')),
            ],
        ),
        migrations.CreateModel(
            name='BookCollectionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryshop.book')),
                ('collection_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryshop.collection')),
            ],
        ),
    ]
