# Generated by Django 3.2.9 on 2021-11-09 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('isbn', models.IntegerField(verbose_name=13)),
                ('genre', models.CharField(choices=[('HORROR', 'Horror'), ('ROMANC', 'Romance'), ('NONFIC', 'Non-fiction'), ('FANTAS', 'Fantasy'), ('SCIFIC', 'Science Fiction'), ('MYSTER', 'Mystery'), ('HSTFIC', 'Historial Fiction'), ('CHLDRN', 'Childrens'), ('ATOBIO', 'Autobiography'), ('HISTRY', 'History'), ('COOKBK', 'Cookbook')], max_length=6)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libraryshop.author')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=60)),
                ('lastname', models.CharField(max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='BookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_num', models.IntegerField(unique=True, verbose_name=13)),
                ('file', models.CharField(max_length=500)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryshop.book')),
            ],
        ),
    ]
