# Generated by Django 3.2.9 on 2021-11-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('HORROR', 'Horror'), ('ROMANC', 'Romance'), ('NONFIC', 'Non-fiction'), ('FANTAS', 'Fantasy'), ('SCIFIC', 'Science Fiction'), ('MYSTER', 'Mystery'), ('HSTFIC', 'Historial Fiction'), ('CHLDRN', 'Childrens'), ('ATOBIO', 'Autobiography'), ('PHILOS', 'Philosophy'), ('HISTRY', 'History'), ('COOKBK', 'Cookbook')], max_length=6),
        ),
    ]
