# Generated by Django 3.2.9 on 2021-11-15 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userownbook',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryshop.book'),
        ),
        migrations.AlterField(
            model_name='userownbook',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='userownbook',
            unique_together={('user_id', 'book_id')},
        ),
    ]
