# Generated by Django 3.2.9 on 2021-11-13 00:54

from django.db import migrations, models
import django.db.models.deletion
import libraryshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='libraryshop.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_added_db',
            field=models.DateField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_edit_db',
            field=models.DateField(auto_created=True, auto_now=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('HORROR', 'Horror'), ('ROMANC', 'Romance'), ('NONFIC', 'Non-fiction'), ('FANTAS', 'Fantasy'), ('SCIFIC', 'Science Fiction'), ('MYSTER', 'Mystery'), ('HSTFIC', 'Historial Fiction'), ('CHLDRN', 'Childrens'), ('ATOBIO', 'Autobiography'), ('HISTRY', 'History'), ('COOKBK', 'Cookbook')], max_length=6),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='booksection',
            name='chapter_num',
            field=models.PositiveIntegerField(verbose_name='Chapter number'),
        ),
        migrations.AlterField(
            model_name='booksection',
            name='file',
            field=models.FileField(max_length=250, unique=True, upload_to=libraryshop.models.BookSection.book_section_path),
        ),
    ]
