# Generated by Django 3.2.9 on 2021-11-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryshop', '0002_auto_20211110_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isbn',
        ),
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
