# Generated by Django 3.2.9 on 2021-12-02 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryshop', '0003_auto_20211130_2312'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(fields=('name', 'user_id'), name='constraint_collection_uniq_title_per_user'),
        ),
    ]
