# Generated by Django 3.2.9 on 2021-12-04 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraryshop', '0004_collection_constraint_collection_uniq_title_per_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='date_added_db',
            field=models.DateField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
