# Generated by Django 3.2.9 on 2021-12-04 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libraryshop', '0005_collection_date_added_db'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOwnBookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_section_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryshop.booksection')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user_id', 'book_section_id')},
            },
        ),
    ]
