# Generated by Django 3.2.9 on 2021-12-04 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryshop', '0006_userownbooksection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added_db',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='date_edit_db',
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
